config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get 'pages/about', to: 'pages#about'

  resources :articles
  #get 'signup', to: 'users#new'
  resources :users, except: [:new]

  #get 'login', to: 'devise/sessions#new'
  #post 'login', to: 'sessions#create'
  #delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user #konektado ito sa article table which is andon ung article_id.
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  # before_action :require_user, except: [:index, :show]
  # before_action :require_same_user, only: [:edit, :update, :destroy]
  #

  #ang value ng mga edit,update,show at destroy ay ito:
  #> @article = Article.find(params[:id])
  # dyan din ung naka based ung id nung article.

  #
  #
  ########################################################################
  def index
          @articles = Article.paginate(page: params[:page], per_page:5)
  end
  ########################################################################
  def new
          @article = Article.new
  end
  ########################################################################
  def create

          @article = Article.new(article_params)
          @article.user = current_user #THIS IS TEMPORARY ID FOR CREATING ARTICLE WITH USER ID
            if @article.save
               flash[:success] = "This article was successfully Created"
                redirect_to article_path(@article)
            else
              render 'new'
            end
  end
  ########################################################################
  def destroy
            @article.destroy
                  flash[:danger] = "This article was successfully Deleted"
                  redirect_to articles_path
  end
  ########################################################################
  def update
              if @article.update(article_params)
                  flash[:success] = "This article was successfully Updated"
                   redirect_to article_path(@article)
              else
                  render 'edit'
              end
  end
  ########################################################################
  def show
  end
  ########################################################################
  def edit
  end
  ########################################################################
  # PRIVATE FUNCTIONS
  private
  def set_article
            @article = Article.find(params[:id])
  end
  ########################################################################
  def article_params
            params.require(:article).permit(:title, :description)
  end

  # def require_same_user
  #   if current_user != @article.user and !current_user.admin?
  #     flash[:danger] = "You can edit or delete your own articles"
  #     redirect_to root_path
  #   end
  # end




end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">

          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <small>
              Created by: <%= article.user.username if article.user %>,<%= time_ago_in_words(article.created_at) %> ago,
              Last updated: <%= time_ago_in_words(article.updated_at) %> ago
            </small>
          </div>
        </div>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
        <div class="article-actions" align="center">
          <%= link_to "Edit this Article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete this article", article_path(article), method: :delete, data: {confirm: "Are you sure you want to delete the article"}, class: "btn btn-xs btn-danger" %>
        </div>
          <%end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1><center>Edit Existing Article</center></h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>
  <center> Listing all articles</center>
</h1>
<div class="center">
  <%= will_paginate %> <!--#THIS IS FOR PAGINATION-->
</div>
<%= render 'article', obj: @articles%>
<div class="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1><center>Create Article</center></h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<center><h2>Title: <%= @article.title %></h2></center>

<div class="well col-xs-8 col-xs-offset-2">
  <ul class="listing">
    <div class="row center">
      <div class="col-md-4 col-md-offset-4">
        <li>Created by:</li>
        <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
        <li class="article-title">
          <%= link_to @article.user.username, user_path(@article.user) %>
        </li>
        <li>
          <small> <%= pluralize(@article.user.articles.count, "articles") if @article.user.articles %></small>
        </li>
      </div>
    </div>
  </ul>


  <h4 class="center description"><strong>Description</strong></h4>
  <hr>
  <center><%= simple_format(@article.description) %></center>
  <div class="article-actions" align="center">
    <% if logged_in? && (current_user == @article.user || current_user.admin?)%>
    <%= link_to "Edit this Article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete this article", article_path(@article), method: :delete, data: { confirm:"Are you sure you want to delete the article"}, class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>